---
title: "Lab 02 - Global plastic waste"
author: "Fabio Pena"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message = FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
```


## Load & join data sets

```{r load-data, message = FALSE}
data1 <- read_csv("data/mismanaged-plastic-waste-per-capita.csv")
data2 <- read_csv2("data/per-capita-ocean-plastic-waste.txt")
data3 <- read_tsv("data/UN_country_population.tsv")
data4 <- read_excel("data/UN_country_region.xlsx")



```



```{r join-data, message = FALSE}
plastic_data_all <- data1

plastic_data_all <- data2 %>%
  select(-name) %>%
  left_join(plastic_data_all, by = "code")

plastic_data_all <- data3 %>%
  select(-name) %>%
  right_join(plastic_data_all, by = "code")

plastic_data_all <- data4 %>%
  select(-name) %>%
  right_join(plastic_data_all, by = "code")



```


```{r print-data, message = FALSE}
# Member 2 (pair 1) adds code here to view the first 10 rows of 'plastic_data_all'



```



## Exercises

### Ex 1.

```{r Ex1, message = FALSE}
plastic_data_all %>%
  count(region, sort = TRUE)



```



### Ex 2.

```{r Ex2, message = FALSE}
plastic_data_all <- plastic_data_all %>%
  mutate(total_mismanage_plastic = mismanaged_plastic * population)

plastic_data_all %>%
  group_by(region) %>%
  summarise(mean_total = mean(total_mismanage_plastic, na.rm = TRUE)) %>%
  arrange(desc(mean_total))

```


### Ex 3.

```{r Ex3, message = FALSE}
plastic_data_all <- plastic_data_all %>%
  mutate(pct_mismanaged_plastic_ocean =
           mismanaged_plastic_ocean / mismanaged_plastic * 100)

plastic_data_all %>%
  group_by(region) %>%
  summarise(median_pct = median(pct_mismanaged_plastic_ocean))

plastic_data_all %>% filter(code == "SOM")

plastic_data_all %>%
  mutate(pct_mismanaged_plastic_ocean =
           mismanaged_plastic_ocean / mismanaged_plastic * 100) %>%
  drop_na() %>%
  group_by(region) %>%
  summarise(median_pct = median(pct_mismanaged_plastic_ocean)) %>%
  arrange(median_pct)

```


### Ex 4.

```{r Ex4, message = FALSE}
plastic_data_all <- plastic_data_all %>%
  rename(
    pop = population,
    mis_plastic = mismanaged_plastic,
    mis_ocean = mismanaged_plastic_ocean,
    total_mis = total_mismanage_plastic,
    pct_ocean = pct_mismanaged_plastic_ocean
  ) %>%
  mutate(region = str_replace_all(region,
                                  "Latin America and The Caribbean", "LAC"))

plastic_data_all %>%
  group_by(region) %>%
  summarise(mean_mis = mean(mis_plastic, na.rm = TRUE)) %>%
  arrange(desc(mean_mis))


```
